-- ============================================
-- BASAR-TISCHBOERSE - DATENBANK VERSION 2
-- ============================================

create table if not exists public.basare (
  id bigint generated by default as identity primary key,
  name text not null,
  ort text,
  veranstaltungsdatum date,
  max_tische integer not null check (max_tische > 0),
  aktiv boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.buchungen (
  id bigint generated by default as identity primary key,
  basar_id bigint not null references public.basare(id) on delete cascade,
  buchungsnummer text unique not null,
  anzahl_tische integer not null check (anzahl_tische between 1 and 3),
  verkaufsbereich text not null check (verkaufsbereich in ('kinder', 'erwachsene')),
  kuchenspende boolean not null default false,
  preis numeric(10,2) not null check (preis >= 0),
  vorname text not null,
  nachname text not null,
  strasse text not null,
  hausnummer text not null,
  plz text not null,
  ort text not null,
  email text not null,
  telefon text,
  zahlungsart text not null check (zahlungsart in ('paypal', 'ueberweisung')),
  zahlungsstatus text not null default 'offen' check (zahlungsstatus in ('offen', 'bezahlt', 'storniert')),
  zahlungsfrist date not null,
  created_at timestamptz not null default now()
);

create or replace function public.pruefe_buchung()
returns trigger
language plpgsql
as $$
declare
  grundpreis numeric(10,2);
  erwarteter_preis numeric(10,2);
  bereits_belegte_tische integer;
  maximale_tische integer;
begin
  grundpreis := case new.anzahl_tische when 1 then 12.00 when 2 then 20.00 when 3 then 25.00 end;
  erwarteter_preis := grundpreis - case when new.kuchenspende then 4.00 else 0.00 end;

  if new.preis <> erwarteter_preis then
    raise exception 'Ungueltiger Buchungspreis';
  end if;

  select max_tische into maximale_tische
  from public.basare
  where id = new.basar_id and aktiv = true
  for update;

  if maximale_tische is null then
    raise exception 'Basar nicht gefunden oder nicht aktiv';
  end if;

  select coalesce(sum(anzahl_tische), 0) into bereits_belegte_tische
  from public.buchungen
  where basar_id = new.basar_id
    and zahlungsstatus <> 'storniert'
    and id is distinct from new.id;

  if bereits_belegte_tische + new.anzahl_tische > maximale_tische then
    raise exception 'Nicht genuegend freie Tische vorhanden';
  end if;

  return new;
end;
$$;

drop trigger if exists buchung_pruefen on public.buchungen;
create trigger buchung_pruefen
before insert or update on public.buchungen
for each row execute function public.pruefe_buchung();

create sequence if not exists public.buchungsnummer_seq;

create or replace function public.get_basar_availability(p_basar_id bigint)
returns table(total_tables integer, booked_tables integer, free_tables integer)
language sql
security definer
set search_path = public
as $$
  select b.max_tische::integer,
         coalesce(sum(case when bu.zahlungsstatus <> 'storniert' then bu.anzahl_tische else 0 end),0)::integer,
         greatest(b.max_tische - coalesce(sum(case when bu.zahlungsstatus <> 'storniert' then bu.anzahl_tische else 0 end),0),0)::integer
  from public.basare b
  left join public.buchungen bu on bu.basar_id = b.id
  where b.id = p_basar_id and b.aktiv = true
  group by b.id, b.max_tische;
$$;

grant execute on function public.get_basar_availability(bigint) to anon, authenticated;

create or replace function public.create_buchung(
  p_basar_id bigint,
  p_anzahl_tische integer,
  p_verkaufsbereich text,
  p_kuchenspende boolean,
  p_vorname text,
  p_nachname text,
  p_strasse text,
  p_hausnummer text,
  p_plz text,
  p_ort text,
  p_email text,
  p_telefon text,
  p_zahlungsart text
)
returns table(buchungsnummer text, preis numeric, zahlungsfrist date)
language plpgsql
security definer
set search_path = public
as $$
declare
  grundpreis numeric(10,2);
  finalpreis numeric(10,2);
  v_buchungsnummer text;
begin
  if p_anzahl_tische not between 1 and 3 then
    raise exception 'Ungueltige Tischanzahl';
  end if;
  if p_verkaufsbereich not in ('kinder','erwachsene') then
    raise exception 'Ungueltiger Verkaufsbereich';
  end if;
  if p_zahlungsart not in ('paypal','ueberweisung') then
    raise exception 'Ungueltige Zahlungsart';
  end if;

  grundpreis := case p_anzahl_tische when 1 then 12.00 when 2 then 20.00 when 3 then 25.00 end;
  finalpreis := grundpreis - case when p_kuchenspende then 4.00 else 0.00 end;
  v_buchungsnummer := 'B-' || to_char(current_date, 'YYYY') || '-' || lpad(nextval('public.buchungsnummer_seq')::text, 6, '0');

  insert into public.buchungen (
    basar_id, buchungsnummer, anzahl_tische, verkaufsbereich, kuchenspende, preis,
    vorname, nachname, strasse, hausnummer, plz, ort, email, telefon,
    zahlungsart, zahlungsstatus, zahlungsfrist
  ) values (
    p_basar_id, v_buchungsnummer, p_anzahl_tische, p_verkaufsbereich, p_kuchenspende, finalpreis,
    p_vorname, p_nachname, p_strasse, p_hausnummer, p_plz, p_ort, p_email, p_telefon,
    p_zahlungsart, 'offen', current_date + 14
  );

  return query select v_buchungsnummer, finalpreis, current_date + 14;
end;
$$;

grant execute on function public.create_buchung(bigint, integer, text, boolean, text, text, text, text, text, text, text, text, text) to anon, authenticated;

alter table public.basare enable row level security;
alter table public.buchungen enable row level security;

drop policy if exists "aktive basare oeffentlich lesbar" on public.basare;
create policy "aktive basare oeffentlich lesbar"
on public.basare for select to anon, authenticated using (aktiv = true);

-- Absichtlich KEINE direkte SELECT/INSERT-Policy fuer buchungen.
-- Buchungen laufen ausschliesslich ueber die kontrollierte Funktion create_buchung().
